### ISSUE TITLE
views

### ISSUE THREAD

**Issue by yujinjcho** [yujinjcho/rcruitme#6]
home page, user page, job submission page, job review page

**Comment by yujinjcho** [comment]
https://themesfor.app/

**Comment by achiu8** [comment]
those look pretty cool. how do you actually get / use them though? need to subscribe and wait for email?

**Comment by yujinjcho** [comment]
Yeah think so. I subscribed.

**Comment by yujinjcho** [comment]
closing this. client related issues on https://github.com/yujinjcho/rcruitme-front/issues
